version: "3"

services:
  psql:
    image: postgres:12
    env_file: .env
    networks:
      - default

  minio-oss:
    image: minio/minio
    env_file: .env
    networks:
      - default
    volumes:
      - /data
    entrypoint: minio server /data
    ports:
      - 39000:9000

  coordinator:
    image: rurikawa-coordinator
    build:
      context: .
      dockerfile: coordinator.Dockerfile
    volumes:
      - ./coordinator/appsettings.dev.json:/app/appsettings.json
      - ./coordinator/certs:/app/certs
    depends_on:
      - psql
      - minio-oss

  judger:
    image: rurikawa-judger
    restart: unless-stopped
    build:
      context: judger
    entrypoint: ["/app/rurikawa", "connect", "coordinator:80"]
    depends_on:
      - coordinator

  caddy:
    image: caddy:2.1.1-alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 38080:80
