[package]
authors = ["Rynco Maekawa <lynzrand@outlook.com>", "Rami3L Li <rami3l@>"]
edition = "2018"
name = "rurikawa-judger"
version = "0.1.9"

[[bin]]
name = "rurikawa"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "*"
async-compat = "0.1"
async-pipe = "0.1"
async-tar = "0.3.0"
async-trait = "0.1.38"
bollard = {path = "3rd_party/bollard"}
broadcaster = {version = "1.0.0", features = ["default-channels"]}
bytes = "*"
chrono = "0.4.15"
clap = "3.0.0-beta.1"
ctrlc = "3.1.6"
dashmap = "3.11.10"
difference = "2.0.0"
dirs = "3.0.1"
err-derive = "*"
fern = "0.6.0"
futures = "0.3.5"
futures_codec = "0.4.1"
http = "*"
hyper = {version = "0.13.7", features = ["stream"]}
libc = "0.2.76"
log = "*"
names = "0.11.0"
once_cell = "1.4.1"
path-absolutize = "3.0.6"
path-slash = "0.1.3"
rand = "0.7.3"
regex = "1.3.9"
reqwest = {version = "0.10.8", features = ["json", "stream"]}
serde = {version = "1.0.115", features = ["derive"]}
serde_json = "1.0.57"
tar = "0.4.29"
tokio = {version = "0.2.22", features = [
  "time",
  "io-util",
  "process",
  "stream",
  "rt-threaded",
  "macros",
]}
tokio-tungstenite = {version = "0.11.0", features = ["tls"]}
tokio-util = "0.3.1"
toml = "0.5.6"
tungstenite = "0.11.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
tokio-test = "0.2.1"
