[package]
authors = ["Rynco Maekawa <lynzrand@outlook.com>"]
edition = "2018"
name = "rurikawa-judger"
version = "0.1.0"

[[bin]]
name = "rurikawa"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "*"
async-trait = "0.1.38"
bollard = "0.8.0"
chrono = "0.4.15"
clap = "3.0.0-beta.1"
ctrlc = "3.1.6"
difference = "2.0.0"
fern = "0.6.0"
futures = "0.3.5"
http = "*"
hyper = {version = "0.13.7", features = ["stream"]}
libc = "0.2.76"
log = "*"
names = "0.11.0"
reqwest = "0.10.8"
serde = {version = "1.0.115", features = ["derive"]}
serde_json = "1.0.57"
tar = "0.4.29"
tokio = {version = "0.2.22", features = [
  "time",
  "io-util",
  "process",
  "stream",
  "rt-threaded",
  "macros",
]}
tokio-tungstenite = "0.11.0"
toml = "0.5.6"
tungstenite = "0.11.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
tokio-test = "0.2.1"
