[package]
name = "rurikawa-judger"
version = "0.1.0"
authors = ["Rynco Maekawa <lynzrand@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "3.0.0-beta.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5.6"
shiplift = "0.6"
tungstenite = "*"
tokio-tungstenite = "0.10.1"
difference = "2.0.0"
# subprocess = "0.2.4"
libc = "0.2.72"
tokio = { version = "0.2.21", features = ["time", "io-util", "process"] }
async-trait = "0.1.36"

[dev-dependencies]
tokio-test = "0.2.1"
