[package]
name = "rurikawa-judger"
version = "0.1.0"
authors = ["Rynco Maekawa <lynzrand@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "3.0.0-beta.1"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
toml = "0.5.6"
# shiplift = "0.6"
tungstenite = "0.11.0"
tokio-tungstenite = "0.10.1"
difference = "2.0.0"
# subprocess = "0.2.4"
libc = "0.2.71"
tokio = { version = "0.2.21", features = [
    "time",
    "io-util",
    "process",
    "stream",
    "rt-threaded",
    "macros",
] }
async-trait = "0.1.36"
futures = "0.3.5"
bollard = "0.6.1"

[dev-dependencies]
tokio-test = "0.2.1"
