name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-coordinator-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: docker.pkg.github.com
          # Docker repository to tag the image with
          repository: buaa-se-compiling/rurikawa/rurikawa-coordinator
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          tag_with_sha: true
          # Path to the build context
          path: .
          dockerfile: coordinator.Dockerfile
          # Adds labels with git repository information to the built image
          add_git_labels: true
          build_args: CI=true

  build-judger-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: docker.pkg.github.com
          # Docker repository to tag the image with
          repository: buaa-se-compiling/rurikawa/rurikawa-judger
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          tag_with_sha: true
          # Path to the build context
          path: judger
          # Adds labels with git repository information to the built image
          add_git_labels: true
          build-args: CI=true

  build-web-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: docker.pkg.github.com
          # Docker repository to tag the image with
          repository: buaa-se-compiling/rurikawa/rurikawa-web
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          tag_with_sha: true
          # Path to the build context
          path: web
          # Adds labels with git repository information to the built image
          add_git_labels: true
          build-args: CI=true

  build-judger:
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   artifact_name: rurikawa
          #   asset_name: rurikawa-linux-amd64-gnu
          #   # target_name: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            artifact_name: rurikawa
            asset_name: rurikawa-linux-amd64-musl
            target_name: x86_64-unknown-linux-musl
          - os: windows-latest
            artifact_name: rurikawa.exe
            asset_name: rurikawa-windows-amd64.exe
          - os: macos-latest
            artifact_name: rurikawa
            asset_name: rurikawa-macos-amd64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build rust
        if: ${{ matrix.target_name == 0 }}
        working-directory: judger
        run: |
          cargo fetch
          cargo build --frozen --release

      - name: install musl tools
        if: ${{ matrix.target_name == 'x86_64-unknown-linux-musl' }}
        run: sudo apt update && sudo apt install musl musl-dev musl-tools

      - name: install libclang (ubuntu)
        if: ${{ matrix.os=='ubuntu-latest' }}
        run: sudo apt-get install pkg-config libclang1

      - name: install libclang (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install llvm -y

      - name: Install rust target
        if: ${{ matrix.target_name != 0 }}
        continue-on-error: true
        run: rustup target add ${{ matrix.target_name }}

      - name: Build rust (targeted)
        if: ${{ matrix.target_name != 0 }}
        working-directory: judger
        run: |
          cargo fetch
          cargo build --frozen --release --target ${{ matrix.target_name }}

      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ matrix.target_name != 0 }}
          if_true: judger/target/${{matrix.target_name}}/release
          if_false: judger/target/release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.condval.outputs.value }}/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
