name: test

on:
  push:
  pull_request:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - name: Build judger
        run: cargo build
        working-directory: ./judger/
      - name: Run unit tests for judger
        # Docker tests are ignored by default, so it should be included here
        run: cargo test -- --include-ignored
        working-directory: ./judger/
        env:
          RUST_LOG: info,rurikawa_judger=trace
