name: test

on:
  push:
  pull_request:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./judger/

      - name: Run unit tests for judger
        # This run does not contain docker tests, and is run in parallel.
        run: cargo test
        working-directory: ./judger/

      - name: Run docker tests for judger
        # Docker tests are ignored by default, so they are included in this run.
        # Also noted that Docker tests are mutating global docker state, 
        # so they must not be run in parallel.
        run: cargo test -- --ignored
        working-directory: ./judger/
        env:
          RUST_TEST_THREADS: 1
    env:
      RUST_LOG: info,rurikawa_judger=trace
      RUST_TEST_TIME_UNIT: 10s,60s
      RUST_TEST_TIME_DOCTEST: 2s,10s
      RUST_TEST_TIME_INTEGRATION: 10s,60s
